package dao;
// Generated Mar 21, 2021, 12:48:35 AM by Hibernate Tools 3.2.2.GA



/**
 * BuyerBuyProductId generated by hbm2java
 */
public class BuyerBuyProductId  implements java.io.Serializable {


     private int buyerId;
     private int productId;

    public BuyerBuyProductId() {
    }

    public BuyerBuyProductId(int buyerId, int productId) {
       this.buyerId = buyerId;
       this.productId = productId;
    }
   
    public int getBuyerId() {
        return this.buyerId;
    }
    
    public void setBuyerId(int buyerId) {
        this.buyerId = buyerId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }




}


