package day2.dao;// default package
// Generated Mar 20, 2021, 3:15:55 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */

public class Category  implements java.io.Serializable {


     private Integer id;
     private String value;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(String value) {
        this.value = value;
    }
    public Category(String value, String description, Set<Product> products) {
       this.value = value;
       this.description = description;
       this.products = products;
    }
   

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }


    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }


    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }


}


