
package day1.lab1.webservice.sei;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0-M2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://webservice.lab1.day1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.AddResponse")
    @Action(input = "http://webservice.lab1.day1/Calculator/addRequest", output = "http://webservice.lab1.day1/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.SubResponse")
    @Action(input = "http://webservice.lab1.day1/Calculator/subRequest", output = "http://webservice.lab1.day1/Calculator/subResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mul", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.MulResponse")
    @Action(input = "http://webservice.lab1.day1/Calculator/mulRequest", output = "http://webservice.lab1.day1/Calculator/mulResponse")
    public int mul(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://webservice.lab1.day1/", className = "day1.lab1.webservice.sei.DivResponse")
    @Action(input = "http://webservice.lab1.day1/Calculator/divRequest", output = "http://webservice.lab1.day1/Calculator/divResponse")
    public int div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
